const cart = new Map();
const currencies = { PKR: ['Rs', 'Pakistani Rupee'], USD: ['$', 'US Dollar'], EUR: ['€', 'Euro'], GBP: ['£', 'British Pound'], AED: ['د.إ', 'UAE Dirham'], SAR: ['﷼', 'Saudi Riyal'], QAR: ['﷼', 'Qatari Riyal'], KWD: ['د.ك', 'Kuwaiti Dinar'], BHD: ['د.ب', 'Bahraini Dinar'], OMR: ['﷼', 'Omani Rial'], INR: ['₹', 'Indian Rupee'], BDT: ['৳', 'Bangladeshi Taka'], LKR: ['Rs', 'Sri Lankan Rupee'], NPR: ['रू', 'Nepalese Rupee'], CNY: ['¥', 'Chinese Yuan'], JPY: ['¥', 'Japanese Yen'], CAD: ['C$', 'Canadian Dollar'], AUD: ['A$', 'Australian Dollar'], NZD: ['NZ$', 'New Zealand Dollar'], ZAR: ['R', 'South African Rand'], TRY: ['₺', 'Turkish Lira'], MYR: ['RM', 'Malaysian Ringgit'], IDR: ['Rp', 'Indonesian Rupiah'], THB: ['฿', 'Thai Baht'], CHF: ['CHF', 'Swiss Franc'] };
const printers = { browser: 'Normal printer / A4', thermal58: 'Thermal printer 58mm', thermal80: 'Thermal printer 80mm' };
const languages = { en: 'English', 'ur-pk': 'Roman Urdu', ur: 'Urdu', hi: 'Hindi', ar: 'Arabic', bn: 'Bangla', pa: 'Punjabi', sd: 'Sindhi', fa: 'Persian', tr: 'Turkish', id: 'Indonesian', ms: 'Malay', zh: 'Chinese', ja: 'Japanese', ko: 'Korean', es: 'Spanish', fr: 'French', de: 'German', it: 'Italian', pt: 'Portuguese', ru: 'Russian', nl: 'Dutch', pl: 'Polish', th: 'Thai', vi: 'Vietnamese', sw: 'Swahili' };
const translations = { en: { greeting: 'Assalam-o-alaikum, Ali', sale: 'Sale counter', inventory: 'Inventory', reports: 'Reports', settings: 'Settings', search: 'Product name or barcode search...', add: 'Add product', clear: 'Clear all', paid: 'Paid & receipt', unpaid: 'Save unpaid', history: 'Sale history', print: 'Print list', configure: 'Configure receipt', empty: 'Select a product', emptyHistory: 'No sales recorded yet.', edit: 'Edit', barcode: 'Barcode', remove: 'Delete' }, 'ur-pk': { greeting: 'Assalam-o-alaikum, Ali', sale: 'Sale counter', inventory: 'Stock', reports: 'Sale history', settings: 'Settings', search: 'Product naam ya barcode search karein...', add: 'Product add karein', clear: 'Sab clear karein', paid: 'Paid aur receipt', unpaid: 'Unpaid save karein', history: 'Sale history', print: 'List print karein', configure: 'Receipt settings', empty: 'Product select karein', emptyHistory: 'Abhi koi sale record nahi hai.', edit: 'Edit', barcode: 'Barcode', remove: 'Delete' } };
const t = key => (translations[settings?.language] || translations.en)[key] || translations.en[key] || key;
const money = value => `${currencies[settings.currency]?.[0] || settings.currency || 'Rs'} ${value.toLocaleString('en-PK')}`;
const productById = id => window.POS_PRODUCTS.find(product => product.id === Number(id));
let products = JSON.parse(localStorage.getItem('posProducts') || 'null') || window.POS_PRODUCTS;
products = products.map(product => ({ ...product, barcode: product.barcode || `PAK${String(product.id).padStart(6, '0')}`, icon: product.icon || (product.category === 'Pharmacy' ? '💊' : product.category === 'Restaurant' ? '🍛' : product.category === 'Retail' ? '👕' : '🛒') }));
window.POS_PRODUCTS = products;
const grid = document.querySelector('#productGrid');
const search = document.querySelector('#search');
const items = document.querySelector('#cartItems');
const toast = document.querySelector('#toast');
const defaultSettings = { company: 'PaK Sale App', tax: 5, currency: 'PKR', printer: 'browser', language: 'en', paymentMethods: ['Cash', 'Card', 'QR'], logo: '', ...(window.POS_INSTALL_SETTINGS || {}) };
let settings = { ...defaultSettings, ...JSON.parse(localStorage.getItem('posSettings') || '{}') };
if (!currencies[settings.currency]) settings.currency = 'PKR';
let drawerBalance = Number(localStorage.getItem('drawerBalance') || 0);
let saleHistory = JSON.parse(localStorage.getItem('saleHistory') || '[]');
let drawerAction = 'open';
let cashFlowAction = 'in';
let scannerStream = null;
let scanAnimation = null;
const taxValue = () => Math.round([...cart].reduce((sum, [id, quantity]) => sum + productById(id).price * quantity, 0) * Number(settings.tax) / 100);
function renderProducts() {
  const query = search.value.trim().toLowerCase();
  const category = document.querySelector('.category.selected').dataset.category;
  grid.innerHTML = products.map(product => { const matchesQuery = product.name.toLowerCase().includes(query) || product.barcode.toLowerCase().includes(query); const matchesCategory = category === 'Sab' || product.category === category; return `<button class="product-card" data-name="${product.name.toLowerCase()}" data-category="${product.category}" data-id="${product.id}" data-price="${product.price}" style="display:${matchesQuery && matchesCategory ? 'flex' : 'none'}"><span class="product-image ${product.category.toLowerCase()}">${product.icon}</span><span class="product-info"><strong>${product.name}</strong><small>${product.stock} ${product.unit} · ${product.barcode}</small><b>${money(product.price)}</b></span><span class="add">+</span><span class="product-tools"><span data-edit="${product.id}">${t('edit')}</span><span data-barcode="${product.id}">${t('barcode')}</span><span data-delete="${product.id}">${t('remove')}</span></span></button>`; }).join('');
}
function setIconText(selector, icon, text) { const element = document.querySelector(selector); if (element) element.innerHTML = `<span>${icon}</span> ${text}`; }
function applyLanguage() { setIconText('.nav-item:nth-child(1)', '▦', t('sale')); setIconText('.nav-item:nth-child(2)', '□', t('inventory')); setIconText('.nav-item:nth-child(3)', '↗', t('reports')); setIconText('.nav-item:nth-child(4)', '⚙', t('settings')); const heading = document.querySelector('.topbar h1'); if (heading) heading.textContent = t('greeting'); const searchInput = document.querySelector('#search'); if (searchInput) searchInput.placeholder = t('search'); const addButton = document.querySelector('#addProduct'); if (addButton) addButton.textContent = `＋ ${t('add')}`; const clearButton = document.querySelector('#clearCart'); if (clearButton) clearButton.textContent = t('clear'); const paidButton = document.querySelector('#checkout'); if (paidButton) paidButton.innerHTML = `${t('paid')} <span>→</span>`; const unpaidButton = document.querySelector('#saveUnpaid'); if (unpaidButton) unpaidButton.textContent = t('unpaid'); const historyTitle = document.querySelector('.history-panel h2'); if (historyTitle) historyTitle.textContent = t('history'); const printButton = document.querySelector('#printHistory'); if (printButton) printButton.textContent = `▣ ${t('print')}`; const settingsButton = document.querySelector('#receiptSettings'); if (settingsButton) settingsButton.textContent = `⚙ ${t('configure')}`; document.querySelectorAll('.category').forEach(button => { if (button.dataset.category === 'Sab') button.textContent = settings.language === 'ur-pk' ? 'Sab' : 'All'; }); renderProducts(); renderCart(); renderHistory(); }
function barcodeSvg(value) { let bits = '101011'; for (const char of value.toUpperCase()) { const code = char.charCodeAt(0); bits += code.toString(2).padStart(7, '0') + '0'; } bits += '1101011'; return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${bits.length * 3} 90" role="img"><rect width="100%" height="100%" fill="white"/>${[...bits].map((bit, index) => bit === '1' ? `<rect x="${index * 3}" y="5" width="3" height="58" fill="black"/>` : '').join('')}<text x="50%" y="82" text-anchor="middle" font-family="Arial" font-size="13">${value}</text></svg>`; }
function printBarcode(product) { const popup = window.open('', '_blank', 'width=420,height=320'); if (!popup) return showToast('Barcode print ke liye popup allow karein'); popup.document.write(`<html><head><title>${product.name} Barcode</title><style>body{text-align:center;font:14px Arial;padding:25px}svg{width:330px;max-width:100%}p{margin:7px}</style></head><body><strong>${product.name}</strong><p>${money(product.price)}</p>${barcodeSvg(product.barcode)}<script>window.print();</script></body></html>`); popup.document.close(); }
function renderCart() {
  if (!cart.size) { items.innerHTML = `<div class="empty-cart">${t('empty')}<br><small>${settings.language === 'ur-pk' ? 'Order yahan nazar aayega' : 'Order will appear here'}</small></div>`; }
  else { items.innerHTML = [...cart].map(([id, quantity]) => { const product = productById(id); return `<div class="cart-item"><span class="item-name">${product.name}</span><span class="qty"><button data-action="minus" data-id="${id}">−</button><span>${quantity}</span><button data-action="plus" data-id="${id}">+</button></span><b class="item-price">${money(product.price * quantity)}</b></div>`; }).join(''); }
  const subtotal = [...cart].reduce((sum, [id, quantity]) => sum + productById(id).price * quantity, 0);
  const tax = taxValue();
  document.querySelector('#subtotal').textContent = money(subtotal);
  document.querySelector('#tax').textContent = money(tax);
  document.querySelector('#total').textContent = money(subtotal + tax);
}
function renderSettings() {
  document.querySelector('#companyName').value = settings.company;
  document.querySelector('#taxRate').value = settings.tax;
  document.querySelector('#currencyCode').value = settings.currency;
  document.querySelector('#printerType').value = settings.printer;
  document.querySelector('#languageCode').value = settings.language;
  document.querySelector('#taxLabel').firstChild.textContent = `Tax (${settings.tax}%) `;
  document.querySelector('#companyPreview').textContent = settings.company;
  document.querySelector('#receiptPreview').textContent = `Tax ${settings.tax}% · Receipt ready`;
  document.querySelector('#drawerBalance').textContent = money(drawerBalance);
  document.querySelector('#logoPreview').innerHTML = settings.logo ? `<img src="${settings.logo}" alt="Company logo">` : 'Logo preview';
}
function renderHistory() {
  const history = document.querySelector('#saleHistory');
  const filter = document.querySelector('#historyFilter').value;
  const filtered = saleHistory.filter(sale => filter === 'all' || sale.status === filter);
  if (!filtered.length) { history.innerHTML = `<div class="empty-history">${settings.language === 'ur-pk' ? 'Is filter mein koi sale nahi hai.' : 'No sales in this filter.'}</div>`; return; }
  history.innerHTML = filtered.slice().reverse().map(sale => `<div class="history-row"><div><strong>${sale.number} <em class="status-${sale.status}">${sale.status}</em></strong><small>${sale.date} · ${sale.payment} · ${sale.items} items</small></div><b>${money(sale.total)}</b></div>`).join('');
}
function renderPaymentMethods() { document.querySelector('#paymentMethods').innerHTML = settings.paymentMethods.map((method, index) => `<button class="payment ${index === 0 ? 'active' : ''}">${method}</button>`).join(''); }
function renderCustomMethods() { document.querySelector('#customMethods').innerHTML = settings.paymentMethods.map(method => `<span>${method}<button type="button" data-remove-payment="${method}">×</button></span>`).join(''); }
function openModal(id) { document.querySelector(`#${id}`).classList.add('visible'); }
function closeModal(id) { document.querySelector(`#${id}`).classList.remove('visible'); }
function addScannedProduct(code) { const product = products.find(item => item.barcode.toLowerCase() === code.trim().toLowerCase()); if (!product) return showToast('Barcode ka product nahi mila'); cart.set(product.id, (cart.get(product.id) || 0) + 1); renderCart(); closeScanner(); showToast(`${product.name} cart mein add ho gaya`); }
function closeScanner() { if (scannerStream) scannerStream.getTracks().forEach(track => track.stop()); scannerStream = null; if (scanAnimation) cancelAnimationFrame(scanAnimation); closeModal('scannerModal'); }
async function startScanner() { openModal('scannerModal'); document.querySelector('#scannerInput').focus(); const video = document.querySelector('#scannerVideo'); const note = document.querySelector('#scannerNote'); if (!('BarcodeDetector' in window) || !navigator.mediaDevices?.getUserMedia) { note.textContent = 'Camera support nahi. USB scanner code input mein scan karein.'; return; } try { scannerStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } } }); video.srcObject = scannerStream; const detector = new BarcodeDetector({ formats: ['ean_13', 'ean_8', 'code_128', 'code_39', 'upc_a', 'upc_e'] }); const scan = async () => { if (!scannerStream) return; try { const results = await detector.detect(video); if (results.length) return addScannedProduct(results[0].rawValue); } catch (error) { note.textContent = 'Camera scan dobara try karein.'; } scanAnimation = requestAnimationFrame(scan); }; scan(); note.textContent = 'Camera ke samne barcode rakhein.'; } catch (error) { note.textContent = 'Camera permission nahi mili. USB scanner use karein.'; } }
function printReceipt() {
  const subtotal = [...cart].reduce((sum, [id, quantity]) => sum + productById(id).price * quantity, 0);
  const tax = taxValue();
  const rows = [...cart].map(([id, quantity]) => `<tr><td>${productById(id).name} x ${quantity}</td><td>${money(productById(id).price * quantity)}</td></tr>`).join('');
  const receipt = window.open('', '_blank', 'width=420,height=650');
  if (!receipt) return showToast('Receipt print ke liye popup allow karein');
  const width = settings.printer === 'thermal58' ? '58mm' : settings.printer === 'thermal80' ? '80mm' : '420px';
  receipt.document.write(`<html><head><title>${settings.company} Receipt</title><style>@page{size:${width} auto;margin:0}body{font:14px Arial;padding:12px;color:#222;max-width:${width};margin:auto}h1{text-align:center;font-size:20px}p{text-align:center;color:#666}table{width:100%;border-collapse:collapse;margin:20px 0}td{padding:7px 0;border-bottom:1px solid #ddd}td:last-child{text-align:right}strong{display:flex;justify-content:space-between;font-size:18px}</style></head><body>${settings.logo ? `<p><img src="${settings.logo}" style="max-width:90px;max-height:60px"></p>` : ''}<h1>${settings.company}</h1><p>Sale receipt · ${new Date().toLocaleString()}</p><table>${rows}</table><p>Subtotal: ${money(subtotal)}<br>Tax (${settings.tax}%): ${money(tax)}</p><strong><span>Total</span><span>${money(subtotal + tax)}</span></strong><p>Thank you for shopping with us</p><script>window.print();</script></body></html>`);
  receipt.document.close();
}
function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2200); }
grid.addEventListener('click', event => { const edit = event.target.closest('[data-edit]'); const remove = event.target.closest('[data-delete]'); const barcode = event.target.closest('[data-barcode]'); if (barcode) { event.stopPropagation(); printBarcode(productById(barcode.dataset.barcode)); return; } if (edit) { event.stopPropagation(); const product = productById(edit.dataset.edit); document.querySelector('#productModalTitle').textContent = 'Edit product'; document.querySelector('#productId').value = product.id; document.querySelector('#productIcon').value = product.icon; document.querySelector('#productName').value = product.name; document.querySelector('#productBarcode').value = product.barcode; document.querySelector('#productCategory').value = product.category; document.querySelector('#productPrice').value = product.price; document.querySelector('#productStock').value = product.stock; document.querySelector('#productUnit').value = product.unit; openModal('productModal'); return; } if (remove) { event.stopPropagation(); const id = Number(remove.dataset.delete); const product = productById(id); if (!window.confirm(`${product.name} delete karna hai?`)) return; products = products.filter(item => item.id !== id); window.POS_PRODUCTS = products; cart.delete(id); localStorage.setItem('posProducts', JSON.stringify(products)); renderProducts(); renderCart(); showToast('Product delete ho gaya'); return; } const card = event.target.closest('.product-card'); if (!card) return; const id = Number(card.dataset.id); cart.set(id, (cart.get(id) || 0) + 1); renderCart(); showToast(`${productById(id).name} order mein add ho gaya`); });
items.addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; const id = Number(button.dataset.id); const next = (cart.get(id) || 0) + (button.dataset.action === 'plus' ? 1 : -1); next > 0 ? cart.set(id, next) : cart.delete(id); renderCart(); });
document.querySelector('#clearCart').addEventListener('click', () => { cart.clear(); renderCart(); });
function completeSale(status) { if (!cart.size) return showToast('Pehle product select karein'); const payment = document.querySelector('.payment.active')?.textContent.trim() || 'Cash'; const total = [...cart].reduce((sum, [id, quantity]) => sum + productById(id).price * quantity, 0) + taxValue(); saleHistory.push({ number: `#${String(10249 + saleHistory.length).padStart(5, '0')}`, date: new Date().toLocaleString(), payment, status, items: [...cart.values()].reduce((sum, quantity) => sum + quantity, 0), total }); localStorage.setItem('saleHistory', JSON.stringify(saleHistory)); if (status === 'paid' && payment === 'Cash') { drawerBalance += total; localStorage.setItem('drawerBalance', drawerBalance); } printReceipt(); cart.clear(); renderCart(); renderSettings(); renderHistory(); showToast(status === 'paid' ? 'Payment complete. Receipt tayyar hai.' : 'Unpaid sale save ho gayi'); }
document.querySelector('#checkout').addEventListener('click', () => completeSale('paid'));
document.querySelector('#saveUnpaid').addEventListener('click', () => completeSale('unpaid'));
document.querySelectorAll('.category').forEach(button => button.addEventListener('click', () => { document.querySelector('.category.selected').classList.remove('selected'); button.classList.add('selected'); renderProducts(); }));
search.addEventListener('input', renderProducts);
document.querySelector('#paymentMethods').addEventListener('click', event => { const button = event.target.closest('.payment'); if (!button) return; document.querySelector('.payment.active')?.classList.remove('active'); button.classList.add('active'); });
document.querySelector('#settingsLink').addEventListener('click', event => { event.preventDefault(); openModal('settingsModal'); });
document.querySelector('#receiptSettings').addEventListener('click', () => openModal('settingsModal'));
document.querySelectorAll('[data-close]').forEach(button => button.addEventListener('click', () => button.dataset.close === 'scannerModal' ? closeScanner() : closeModal(button.dataset.close)));
document.querySelector('#settingsForm').addEventListener('submit', event => { event.preventDefault(); settings.company = document.querySelector('#companyName').value.trim() || defaultSettings.company; settings.tax = Number(document.querySelector('#taxRate').value) || 0; settings.currency = document.querySelector('#currencyCode').value; settings.printer = document.querySelector('#printerType').value; settings.language = document.querySelector('#languageCode').value; localStorage.setItem('posSettings', JSON.stringify(settings)); closeModal('settingsModal'); renderSettings(); renderPaymentMethods(); applyLanguage(); showToast(settings.language === 'ur-pk' ? 'Language aur settings save ho gayi' : 'Language and settings saved'); });
document.querySelector('#companyLogo').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { settings.logo = reader.result; document.querySelector('#logoPreview').innerHTML = `<img src="${reader.result}" alt="Company logo">`; }; reader.readAsDataURL(file); });
document.querySelector('#openDrawer').addEventListener('click', () => { drawerAction = 'open'; document.querySelector('#drawerHeading').textContent = 'Open cash drawer'; document.querySelector('#drawerAmount').value = ''; openModal('drawerModal'); });
document.querySelector('#closeDrawer').addEventListener('click', () => { drawerAction = 'close'; document.querySelector('#drawerHeading').textContent = 'Close & count drawer'; document.querySelector('#drawerAmount').value = drawerBalance; openModal('drawerModal'); });
document.querySelector('#drawerForm').addEventListener('submit', event => { event.preventDefault(); drawerBalance = Number(document.querySelector('#drawerAmount').value) || 0; localStorage.setItem('drawerBalance', drawerBalance); closeModal('drawerModal'); renderSettings(); showToast(drawerAction === 'open' ? 'Cash drawer open ho gaya' : 'Cash drawer close aur count ho gaya'); });
document.querySelector('#cashIn').addEventListener('click', () => { cashFlowAction = 'in'; document.querySelector('#cashFlowHeading').textContent = 'Cash in'; document.querySelector('#cashFlowAmount').value = ''; openModal('cashFlowModal'); });
document.querySelector('#cashOut').addEventListener('click', () => { cashFlowAction = 'out'; document.querySelector('#cashFlowHeading').textContent = 'Cash out'; document.querySelector('#cashFlowAmount').value = ''; openModal('cashFlowModal'); });
document.querySelector('#cashFlowForm').addEventListener('submit', event => { event.preventDefault(); const amount = Number(document.querySelector('#cashFlowAmount').value) || 0; if (cashFlowAction === 'out' && amount > drawerBalance) return showToast('Drawer mein itna cash nahi hai'); drawerBalance += cashFlowAction === 'in' ? amount : -amount; localStorage.setItem('drawerBalance', drawerBalance); closeModal('cashFlowModal'); renderSettings(); showToast(cashFlowAction === 'in' ? 'Cash drawer mein add ho gaya' : 'Cash drawer se cash nikal gaya'); });
document.querySelector('#clearHistory').addEventListener('click', () => { saleHistory = []; localStorage.removeItem('saleHistory'); renderHistory(); showToast('Sale history clear ho gayi'); });
document.querySelector('#scanBarcode').addEventListener('click', startScanner);
document.querySelector('#closeScanner').addEventListener('click', closeScanner);
document.querySelector('#scannerInput').addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); addScannedProduct(event.target.value); event.target.value = ''; } });
document.querySelector('#historyFilter').addEventListener('change', renderHistory);
document.querySelector('#printHistory').addEventListener('click', () => { const filter = document.querySelector('#historyFilter').value; const list = saleHistory.filter(sale => filter === 'all' || sale.status === filter); const popup = window.open('', '_blank', 'width=700,height=700'); if (!popup) return showToast('Print list ke liye popup allow karein'); popup.document.write(`<html><head><title>${settings.company} Sale List</title><style>body{font:14px Arial;padding:25px}h1{text-align:center}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #ddd;padding:9px;text-align:left}.total{text-align:right}</style></head><body><h1>${settings.company} - ${filter === 'all' ? 'All' : filter} sales</h1><table><tr><th>Sale</th><th>Date</th><th>Payment</th><th>Status</th><th class="total">Total</th></tr>${list.map(sale => `<tr><td>${sale.number}</td><td>${sale.date}</td><td>${sale.payment}</td><td>${sale.status}</td><td class="total">${money(sale.total)}</td></tr>`).join('')}</table><script>window.print();</script></body></html>`); popup.document.close(); });
document.querySelector('#addPaymentMethod').addEventListener('click', () => { const input = document.querySelector('#customPayment'); const method = input.value.trim(); if (!method) return showToast('Payment method ka naam likhein'); if (settings.paymentMethods.includes(method)) return showToast('Yeh method pehle se mojood hai'); settings.paymentMethods.push(method); input.value = ''; renderCustomMethods(); renderPaymentMethods(); });
document.querySelector('#customMethods').addEventListener('click', event => { const button = event.target.closest('[data-remove-payment]'); if (!button || settings.paymentMethods.length <= 1) return; settings.paymentMethods = settings.paymentMethods.filter(method => method !== button.dataset.removePayment); renderCustomMethods(); renderPaymentMethods(); });
document.querySelector('#addProduct').addEventListener('click', () => { document.querySelector('#productModalTitle').textContent = 'Add product'; document.querySelector('#productForm').reset(); document.querySelector('#productId').value = ''; document.querySelector('#productIcon').value = '📦'; document.querySelector('#productBarcode').value = `PAK${String(products.length + 1).padStart(6, '0')}`; openModal('productModal'); });
document.querySelector('#productForm').addEventListener('submit', event => { event.preventDefault(); const id = Number(document.querySelector('#productId').value); const product = { id: id || (products.length ? Math.max(...products.map(item => item.id)) + 1 : 1), icon: document.querySelector('#productIcon').value, name: document.querySelector('#productName').value.trim(), category: document.querySelector('#productCategory').value, barcode: document.querySelector('#productBarcode').value.trim().toUpperCase() || `PAK${String(Date.now()).slice(-6)}`, price: Number(document.querySelector('#productPrice').value), stock: Number(document.querySelector('#productStock').value), unit: document.querySelector('#productUnit').value.trim() || 'item' }; if (!product.name || product.price < 0 || product.stock < 0) return showToast('Product details check karein'); products = id ? products.map(item => item.id === id ? product : item) : [...products, product]; window.POS_PRODUCTS = products; localStorage.setItem('posProducts', JSON.stringify(products)); closeModal('productModal'); renderProducts(); showToast(id ? 'Product update ho gaya' : 'Product add ho gaya'); });
const currencyField = document.createElement('label'); currencyField.textContent = 'Currency'; currencyField.innerHTML += `<select id="currencyCode">${Object.entries(currencies).map(([code, data]) => `<option value="${code}">${code} - ${data[1]} (${data[0]})</option>`).join('')}</select>`; document.querySelector('#companyLogo').parentElement.before(currencyField);
const printerField = document.createElement('label'); printerField.textContent = 'Receipt printer'; printerField.innerHTML += `<select id="printerType">${Object.entries(printers).map(([code, name]) => `<option value="${code}">${name}</option>`).join('')}</select>`; document.querySelector('#companyLogo').parentElement.before(printerField);
const languageField = document.createElement('label'); languageField.textContent = 'Language'; languageField.innerHTML += `<select id="languageCode">${Object.entries(languages).map(([code, name]) => `<option value="${code}">${name}</option>`).join('')}</select>`; document.querySelector('#companyLogo').parentElement.before(languageField);
renderSettings();
renderPaymentMethods();
renderCustomMethods();
renderHistory();
renderProducts();
renderCart();
applyLanguage();
